# Generated by Django 4.1.7 on 2023-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_about_birthday_about_degree_about_text_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=15000),
        ),
    ]
